baseURL: https://demo.gethugothemes.com/liva/
languageCode: nl
title: Koelstof | Online tijdschrift voor milieu-activisme
theme: liva-hugo
summaryLength: '10'
paginate: 6
disqusShortname: ''
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  author: ''
  cookies:
    enable: yes
    expire_days: 2
  copyright: '| copyright &copy; 2022 Valentijn Prové met [Themefisher](https://themefisher.com/hugo-themes/)
    Alle rechten voorbehouden |'
  description: ''
  email: info.koelstof@gmail.com
  googleAnalitycsID: Your ID
  home: Home
  location: ''
  logo: images/logo.png
  mobile: ''
  newsletter:
    content: Wil je graag via e-mail op de hoogte gehouden worden van onze nieuwe edities? Laat dan hieronder je contactgegevens achter!
    enable: yes
    title: Ontvang de nieuwsbrief van Koelstof!
  plugins:
    css:
      - URL: plugins/bootstrap/bootstrap.min.css
      - URL: plugins/slick/slick.css
      - URL: plugins/themify-icons/themify-icons.css
      - URL: plugins/venobox/venobox.css
    js:
      - URL: plugins/jQuery/jquery.min.js
      - URL: plugins/bootstrap/bootstrap.min.js
      - URL: plugins/slick/slick.min.js
      - URL: plugins/venobox/venobox.min.js
      - URL: plugins/search/fuse.min.js
      - URL: plugins/search/mark.js
      - URL: plugins/search/search.js
  preloader:
    enable: yes
    preloader: ''
  search:
    enable: yes
  social:
    - icon: ti-facebook
      link: 'https://www.facebook.com/koelstofblad/'
      title: facebook
    - icon: ti-twitter-alt
      link: 'https://twitter.com/koelstofblad'
      title: twitter
    - icon: ti-instagram
      link: 'https://www.instagram.com/koelstofblad/'
      title: instagram
menu:
  footer:
    - URL: about
      name: Koelwat?
      weight: 1
    - URL: blog
      name: Alle artikels
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
  main:
    - URL: about
      name: Koelwat?
      weight: 1
    - URL: blog
      name: Alle artikels
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
